#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=${SCRIPT_DIR}/../
if [ ! -d "${PROJECT_DIR}/.git" ]; then
  PROJECT_DIR=${PROJECT_DIR}../
fi

make -f ${PROJECT_DIR}Makefile pre-commit
