### {{cookiecutter.model_name.capitalize()}} successfully created
POST {{ServerUrl}}/{{cookiecutter.project_name}}/create-{{cookiecutter.model_name}}
Content-Type: application/json
Origin: {{Origin}}
Authorization: {{BearerToken}}

{
  "{{cookiecutter.model_name}}Id": "1f066b37-c8f5-40cb-bf7b-5b7eda60dd27",
  "model": "Google Pixel 3",
  "hardwareVersion": "Qualcomm Snapdragon 845",
  "operatingSystemVersion": "Android 9.0",
  "appVersion": "1.2.2",
  "apiLevel": "28",
  "securityPatch": "2021-04-20",
  "isNfcAvailable": true,
  "isNfcEnabled": true
}

> 

###
