// Code generated by MockGen. DO NOT EDIT.
// Source: ./{{cookiecutter.model_name}}.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/divilo/{{cookiecutter.project_name}}-back/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// Mock{{cookiecutter.model_name.capitalize()}}Service is a mock of {{cookiecutter.model_name.capitalize()}}Service interface.
type Mock{{cookiecutter.model_name.capitalize()}}Service struct {
	ctrl     *gomock.Controller
	recorder *Mock{{cookiecutter.model_name.capitalize()}}ServiceMockRecorder
}

// Mock{{cookiecutter.model_name.capitalize()}}ServiceMockRecorder is the mock recorder for Mock{{cookiecutter.model_name.capitalize()}}Service.
type Mock{{cookiecutter.model_name.capitalize()}}ServiceMockRecorder struct {
	mock *Mock{{cookiecutter.model_name.capitalize()}}Service
}

// NewMock{{cookiecutter.model_name.capitalize()}}Service creates a new mock instance.
func NewMock{{cookiecutter.model_name.capitalize()}}Service(ctrl *gomock.Controller) *Mock{{cookiecutter.model_name.capitalize()}}Service {
	mock := &Mock{{cookiecutter.model_name.capitalize()}}Service{ctrl: ctrl}
	mock.recorder = &Mock{{cookiecutter.model_name.capitalize()}}ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock{{cookiecutter.model_name.capitalize()}}Service) EXPECT() *Mock{{cookiecutter.model_name.capitalize()}}ServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mock{{cookiecutter.model_name.capitalize()}}Service) Create(ctx context.Context, {{cookiecutter.model_name}} model.{{cookiecutter.model_name.capitalize()}}) (model.{{cookiecutter.model_name.capitalize()}}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, {{cookiecutter.model_name}})
	ret0, _ := ret[0].(model.{{cookiecutter.model_name.capitalize()}})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *Mock{{cookiecutter.model_name.capitalize()}}ServiceMockRecorder) Create(ctx, {{cookiecutter.model_name}} interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mock{{cookiecutter.model_name.capitalize()}}Service)(nil).Create), ctx, {{cookiecutter.model_name}})
}
